name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: BuildPackages
      run: ./build.sh

    - name: Archive production artifacts - windows
      uses: actions/upload-artifact@v2
      with:
        path: |
          dist/runPipeline.windows.amd64.tar.gz

    - name: Archive production artifacts - linux
      uses: actions/upload-artifact@v2
      with:
        path: |
          dist/runPipeline.linux.amd64.tar.gz

    - name: Archive production artifacts - macos
      uses: actions/upload-artifact@v2
      with:
        path: |
          dist/runPipeline.darwin.amd64.tar.gz

